#pragma once

#define WINDOW_MIN_WIDTH 800
#define WINDOW_MIN_HEIGHT 600

#define MAIN_FONT "assets/fonts/roboto-regular.ttf"
#define MAIN_CONFIG "config.txt"

#define DEFAULT_EXPRESSION "x^2"

#define SETTINGS_LABELS_X 128
#define SETTINGS_COMPONENTS_X 128 + 32
#define SETTINGS_ENTRIES_START_Y 128
#define SETTINGS_ENTRIES_Y_OFFSET 32
#define SETTINGS_ENTRIES_Y_MINI_SEP 8

#define SETTINGS_ENTRY_YS(i, s) (SETTINGS_ENTRIES_START_Y + SETTINGS_ENTRIES_Y_OFFSET * i + SETTINGS_ENTRIES_Y_MINI_SEP * s)
#define SETTINGS_ENTRY_Y(i) (SETTINGS_ENTRIES_START_Y + SETTINGS_ENTRIES_Y_OFFSET * i)